# Generated by Django 5.0.3 on 2024-04-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='UserImages/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='service_type',
            field=models.ManyToManyField(blank=True, to='utils.service'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='utils.specialization'),
        ),
    ]
