# Generated by Django 5.0.3 on 2024-04-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_birth_date_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
