# Generated by Django 5.0.3 on 2024-04-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_passport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='meeting',
            field=models.URLField(blank=True, null=True),
        ),
    ]
