# Generated by Django 5.0.3 on 2024-04-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='specialization',
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
