# Generated by Django 5.0.3 on 2024-04-24 11:17

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_invoice_created_date_invoice_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('CASH', 'Cash')], max_length=10, null=utils.models.Invoice.Type),
            preserve_default=utils.models.Invoice.Type,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='active',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
    ]
